### ISSUE TITLE
Regarding Multiplication and exponent

### ISSUE THREAD

**Issue by Dibya123-ui** [dawsonjon/fpu#23]
Sir I was going through your code for the implementation of IEEE 754 floatingpoint multiplier. I noticed that you used z_e <= a_e + b_e + 1; product <= a_m * b_m * 4; but I was bit confused as I think the code should be z_e <= a_e + b_e + 127; product <= a_m * b_m ;. But your syntax gives the correct answer but mine does not. Can you explain the logic behind using it?

**Comment by dawsonjon** [comment]
Hi, 

Thanks very much for your comment I will do my best to answer.  

You are correct that the IEEE format uses a bias of 127 to represent the exponent, but in this implementation I use normal (2s complement) signed numbers internally. The unpack state converts from IEEE to the native format by subtracting 127, then the pack state adds 127 to convert back to the IEEE format. Using 2's complement arithmetic, there is no need to worry about the bias when adding the exponents. This is why I don't add 127.

When the mantissas are multiplied, the operands each have 1 integer bit (and 23 fraction bits), so the result naturally has 2 integer bits (and 46 fraction bits). I want the result to have 1 integer bit rather than 2, so I simultaneously shift the mantissa of the result right by one place, and add one to the exponent. The shifting of the mantissa is implicit in `z_m <= product[49:26];`, but I need to explicitly add 1 to the exponent in `z_e <= a_e + b_e + 1;` this is where the +1 comes from.

I also add another two bits to accommodate the guard and round bits giving 50 bits total in the product. I want to add these additional bits (zeros) to the right hand side (fraction bits), so I shift 2 places to the left by multiplying by 4. `product <= a_m * b_m * 4;`  

Hope this helps
Thanks
Jon
